name: flutter_template
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  page_transition: ^2.2.1
  intl: ^0.20.2
  google_fonts: ^6.3.0
  package_info_plus: ^8.3.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  toastification: ^3.0.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:
